theme: jekyll-theme-cayman
title: WhiteNet: Zero-Day Phishing Website Detection by Visual Whitelists
description: Sahar Abdelnabi, Katharina Krombholz and Mario Fritz
CISPA Helmholtz Center for Information Security
